//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for Departamento-related data. This includes creating unique cache keys for 
//       various departamento queries (such as getting all departamentos, departamentos by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for Departamento-related data.
/// </summary>
public static class DepartamentoCacheKey
{
    public const string GetAllCacheKey = "all-Departamentos";
    public static string GetPaginationCacheKey(string parameters) {
        return $"DepartamentoCacheKey:DepartamentosWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"DepartamentoCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"DepartamentoCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"DepartamentoCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "departamento" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

