//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Defines permission constants for departamento operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Departamento Permissions")]
    [Description("Set permissions for departamento operations.")]
    public static class Departamentos
    {
        [Description("Allows viewing departamento details.")]
        public const string View = "Permissions.Departamentos.View";
        [Description("Allows creating departamento records.")]
        public const string Create = "Permissions.Departamentos.Create";
        [Description("Allows modifying existing departamento details.")]
        public const string Edit = "Permissions.Departamentos.Edit";
        [Description("Allows deleting departamento records.")]
        public const string Delete = "Permissions.Departamentos.Delete";
        [Description("Allows printing departamento details.")]
        public const string Print = "Permissions.Departamentos.Print";
        [Description("Allows searching departamento records.")]
        public const string Search = "Permissions.Departamentos.Search";
        [Description("Allows exporting departamento records.")]
        public const string Export = "Permissions.Departamentos.Export";
        [Description("Allows importing departamento records.")]
        public const string Import = "Permissions.Departamentos.Import";
    }
}

public class DepartamentosAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
