//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for Ejemplo-related data. This includes creating unique cache keys for 
//       various ejemplo queries (such as getting all ejemplos, ejemplos by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for Ejemplo-related data.
/// </summary>
public static class EjemploCacheKey
{
    public const string GetAllCacheKey = "all-Ejemplos";
    public static string GetPaginationCacheKey(string parameters) {
        return $"EjemploCacheKey:EjemplosWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"EjemploCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"EjemploCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"EjemploCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "ejemplo" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

