//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for CreateEjemploCommand: enforces max lengths and required fields for Ejemplo entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.Create;

public class CreateEjemploCommandValidator : AbstractValidator<CreateEjemploCommand>
{
        public CreateEjemploCommandValidator()
        {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.PhoneNumber).MaximumLength(255); 
    RuleFor(v => v.Country).MaximumLength(255); 

        }
       
}

