//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query to retrieve a ejemplo by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same ejemplo.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Ejemplos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Queries.GetById;

public class GetEjemploByIdQuery : ICacheableRequest<Result<EjemploDto>>
{
   public required int Id { get; set; }
   public string CacheKey => EjemploCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
}

public class GetEjemploByIdQueryHandler :
     IRequestHandler<GetEjemploByIdQuery, Result<EjemploDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetEjemploByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<EjemploDto>> Handle(GetEjemploByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Ejemplos.ApplySpecification(new EjemploByIdSpecification(request.Id))
                                                .ProjectTo<EjemploDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Ejemplo with id: [{request.Id}] not found.");
        return await Result<EjemploDto>.SuccessAsync(data);
    }
}
