//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a specification for filtering a Departamento entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering Departamentos by their ID.
/// </summary>
public class DepartamentoByIdSpecification : Specification<Departamento>
{
    public DepartamentoByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}