//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Import command & template for ejemplos.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Ejemplos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.Import;

    public class ImportEjemplosCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => EjemploCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
        public ImportEjemplosCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateEjemplosTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportEjemplosCommandHandler : 
                 IRequestHandler<CreateEjemplosTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportEjemplosCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportEjemplosCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly EjemploDto _dto = new();
        private readonly IMapper _mapper;
        public ImportEjemplosCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportEjemplosCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportEjemplosCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, EjemploDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x=>x.Name)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Description)], (row, item) => item.Description = row[_localizer[_dto.GetMemberDescription(x=>x.Description)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Email)], (row, item) => item.Email = row[_localizer[_dto.GetMemberDescription(x=>x.Email)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)], (row, item) => item.PhoneNumber = row[_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Country)], (row, item) => item.Country = row[_localizer[_dto.GetMemberDescription(x=>x.Country)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Ejemplos.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<Ejemplo>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new EjemploCreatedEvent(item));
                        await db.Ejemplos.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateEjemplosTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.Name)], 
_localizer[_dto.GetMemberDescription(x=>x.Description)], 
_localizer[_dto.GetMemberDescription(x=>x.Email)], 
_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)], 
_localizer[_dto.GetMemberDescription(x=>x.Country)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

