//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for ImportEjemplosCommand: ensures the Data property is non-null and non-empty for ejemplo import.
// Docs: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.Import;

public class ImportEjemplosCommandValidator : AbstractValidator<ImportEjemplosCommand>
{
        public ImportEjemplosCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

