//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query to retrieve a departamento by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same departamento.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Departamentos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Caching;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Queries.GetById;

public class GetDepartamentoByIdQuery : ICacheableRequest<Result<DepartamentoDto>>
{
   public required int Id { get; set; }
   public string CacheKey => DepartamentoCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => DepartamentoCacheKey.Tags;
}

public class GetDepartamentoByIdQueryHandler :
     IRequestHandler<GetDepartamentoByIdQuery, Result<DepartamentoDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetDepartamentoByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<DepartamentoDto>> Handle(GetDepartamentoByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Departamentos.ApplySpecification(new DepartamentoByIdSpecification(request.Id))
                                                .ProjectTo<DepartamentoDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Departamento with id: [{request.Id}] not found.");
        return await Result<DepartamentoDto>.SuccessAsync(data);
    }
}
