//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for CreateDepartamentoCommand: enforces max lengths and required fields for Departamento entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/departamento
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Commands.Create;

public class CreateDepartamentoCommandValidator : AbstractValidator<CreateDepartamentoCommand>
{
        public CreateDepartamentoCommandValidator()
        {
                RuleFor(v => v.Nombre).MaximumLength(255); 
    RuleFor(v => v.Descripcion).MaximumLength(255); 
    RuleFor(v => v.EncargadoId).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

        }
       
}

