//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles EjemploDeletedEvent: triggered when a ejemplo is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.EventHandlers;

    public class EjemploDeletedEventHandler : INotificationHandler<EjemploDeletedEvent>
    {
        private readonly ILogger<EjemploDeletedEventHandler> _logger;

        public EjemploDeletedEventHandler(
            ILogger<EjemploDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(EjemploDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
