//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles EjemploUpdatedEvent: triggered when a ejemplo is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.EventHandlers;

    public class EjemploUpdatedEventHandler : INotificationHandler<EjemploUpdatedEvent>
    {
        private readonly ILogger<EjemploUpdatedEventHandler> _logger;

        public EjemploUpdatedEventHandler(
            ILogger<EjemploUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(EjemploUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
