//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles EjemploCreatedEvent: triggered when a new ejemplo is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.EventHandlers;

public class EjemploCreatedEventHandler : INotificationHandler<EjemploCreatedEvent>
{
        private readonly ILogger<EjemploCreatedEventHandler> _logger;

        public EjemploCreatedEventHandler(
            ILogger<EjemploCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(EjemploCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
