//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for UpdateDepartamentoCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a departamento.
// Docs: https://docs.cleanarchitectureblazor.com/features/departamento
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Commands.Update;

public class UpdateDepartamentoCommandValidator : AbstractValidator<UpdateDepartamentoCommand>
{
        public UpdateDepartamentoCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Nombre).MaximumLength(255); 
    RuleFor(v => v.Descripcion).MaximumLength(255); 
    RuleFor(v => v.EncargadoId).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

          
        }
    
}

