//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query to retrieve all departamentos from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Departamentos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Queries.GetAll;

public class GetAllDepartamentosQuery : ICacheableRequest<IEnumerable<DepartamentoDto>>
{
   public string CacheKey => DepartamentoCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => DepartamentoCacheKey.Tags;
}

public class GetAllDepartamentosQueryHandler :
     IRequestHandler<GetAllDepartamentosQuery, IEnumerable<DepartamentoDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllDepartamentosQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<DepartamentoDto>> Handle(GetAllDepartamentosQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Departamentos.ProjectTo<DepartamentoDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


