//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Configures the properties and behaviors for the `Departamento` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class DepartamentoConfiguration : IEntityTypeConfiguration<Departamento>
{
    public void Configure(EntityTypeBuilder<Departamento> builder)
    {
            builder.Property(x => x.Nombre).HasMaxLength(255); 
    builder.Property(x => x.Descripcion).HasMaxLength(255); 
    builder.Property(x => x.EncargadoId).HasMaxLength(255); 
    builder.Property(x => x.TenantId).HasMaxLength(255); 
    builder.HasOne(x => x.Tenant).WithMany().HasForeignKey(x => x.TenantId); 
    builder.Navigation(e => e.Tenant).AutoInclude(); 

        builder.Ignore(e => e.DomainEvents);
    }
}


