//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Defines permission constants for ejemplo operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Ejemplo Permissions")]
    [Description("Set permissions for ejemplo operations.")]
    public static class Ejemplos
    {
        [Description("Allows viewing ejemplo details.")]
        public const string View = "Permissions.Ejemplos.View";
        [Description("Allows creating ejemplo records.")]
        public const string Create = "Permissions.Ejemplos.Create";
        [Description("Allows modifying existing ejemplo details.")]
        public const string Edit = "Permissions.Ejemplos.Edit";
        [Description("Allows deleting ejemplo records.")]
        public const string Delete = "Permissions.Ejemplos.Delete";
        [Description("Allows printing ejemplo details.")]
        public const string Print = "Permissions.Ejemplos.Print";
        [Description("Allows searching ejemplo records.")]
        public const string Search = "Permissions.Ejemplos.Search";
        [Description("Allows exporting ejemplo records.")]
        public const string Export = "Permissions.Ejemplos.Export";
        [Description("Allows importing ejemplo records.")]
        public const string Import = "Permissions.Ejemplos.Import";
    }
}

public class EjemplosAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
