//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Command for adding/editing a ejemplo entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.AddEdit;

public class AddEditEjemploCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Phone number")]
    public string? PhoneNumber {get;set;} 
    [Description("Country")]
    public string? Country {get;set;} 


      public string CacheKey => EjemploCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<EjemploDto, AddEditEjemploCommand>(MemberList.None);
            CreateMap<AddEditEjemploCommand, Ejemplo>(MemberList.None);
        }
    }
}

public class AddEditEjemploCommandHandler : IRequestHandler<AddEditEjemploCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditEjemploCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditEjemploCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id > 0)
        {
            var item = await db.Ejemplos.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Ejemplo with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new EjemploUpdatedEvent(item));
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Ejemplo>(request);
            // raise a create domain event
			item.AddDomainEvent(new EjemploCreatedEvent(item));
            db.Ejemplos.Add(item);
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

