//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Import command & template for departamentos.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/departamento
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Departamentos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Commands.Import;

    public class ImportDepartamentosCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => DepartamentoCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => DepartamentoCacheKey.Tags;
        public ImportDepartamentosCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateDepartamentosTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportDepartamentosCommandHandler : 
                 IRequestHandler<CreateDepartamentosTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportDepartamentosCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportDepartamentosCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly DepartamentoDto _dto = new();
        private readonly IMapper _mapper;
        public ImportDepartamentosCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportDepartamentosCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportDepartamentosCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, DepartamentoDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.Nombre)], (row, item) => item.Nombre = row[_localizer[_dto.GetMemberDescription(x=>x.Nombre)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Descripcion)], (row, item) => item.Descripcion = row[_localizer[_dto.GetMemberDescription(x=>x.Descripcion)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.EncargadoId)], (row, item) => item.EncargadoId = row[_localizer[_dto.GetMemberDescription(x=>x.EncargadoId)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.TenantId)], (row, item) => item.TenantId = row[_localizer[_dto.GetMemberDescription(x=>x.TenantId)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Departamentos.AnyAsync(x => x.Nombre == dto.Nombre, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<Departamento>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new DepartamentoCreatedEvent(item));
                        await db.Departamentos.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateDepartamentosTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.Nombre)], 
_localizer[_dto.GetMemberDescription(x=>x.Descripcion)], 
_localizer[_dto.GetMemberDescription(x=>x.EncargadoId)], 
_localizer[_dto.GetMemberDescription(x=>x.TenantId)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

