//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for ImportDepartamentosCommand: ensures the Data property is non-null and non-empty for departamento import.
// Docs: https://docs.cleanarchitectureblazor.com/features/departamento
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Commands.Import;

public class ImportDepartamentosCommandValidator : AbstractValidator<ImportDepartamentosCommand>
{
        public ImportDepartamentosCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

