//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Command and handler for deleting Ejemplo entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.Delete;

public class DeleteEjemploCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => EjemploCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
  public DeleteEjemploCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteEjemploCommandHandler : 
             IRequestHandler<DeleteEjemploCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteEjemploCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteEjemploCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Ejemplos.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new EjemploDeletedEvent(item));
            db.Ejemplos.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

