//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for DeleteEjemploCommand: ensures the ID list for ejemplo is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/ejemplo
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Commands.Delete;

public class DeleteEjemploCommandValidator : AbstractValidator<DeleteEjemploCommand>
{
        public DeleteEjemploCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

