//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query for retrieving ejemplos with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Ejemplos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Queries.Pagination;

public class EjemplosWithPaginationQuery : EjemploAdvancedFilter, ICacheableRequest<PaginatedData<EjemploDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => EjemploCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
    public EjemploAdvancedSpecification Specification => new EjemploAdvancedSpecification(this);
}
    
public class EjemplosWithPaginationQueryHandler :
         IRequestHandler<EjemplosWithPaginationQuery, PaginatedData<EjemploDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public EjemplosWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<EjemploDto>> Handle(EjemplosWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Ejemplos.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Ejemplo, EjemploDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}