//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles DepartamentoUpdatedEvent: triggered when a departamento is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Departamentos.EventHandlers;

    public class DepartamentoUpdatedEventHandler : INotificationHandler<DepartamentoUpdatedEvent>
    {
        private readonly ILogger<DepartamentoUpdatedEventHandler> _logger;

        public DepartamentoUpdatedEventHandler(
            ILogger<DepartamentoUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(DepartamentoUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
