//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles DepartamentoDeletedEvent: triggered when a departamento is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Departamentos.EventHandlers;

    public class DepartamentoDeletedEventHandler : INotificationHandler<DepartamentoDeletedEvent>
    {
        private readonly ILogger<DepartamentoDeletedEventHandler> _logger;

        public DepartamentoDeletedEventHandler(
            ILogger<DepartamentoDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(DepartamentoDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
