//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Handles DepartamentoCreatedEvent: triggered when a new departamento is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Departamentos.EventHandlers;

public class DepartamentoCreatedEventHandler : INotificationHandler<DepartamentoCreatedEvent>
{
        private readonly ILogger<DepartamentoCreatedEventHandler> _logger;

        public DepartamentoCreatedEventHandler(
            ILogger<DepartamentoCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(DepartamentoCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
