//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Domain event for when a departamento is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class DepartamentoUpdatedEvent : DomainEvent
    {
        public DepartamentoUpdatedEvent(Departamento item)
        {
            Item = item;
        }

        public Departamento Item { get; }
    }

