//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Domain event for when a new departamento is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class DepartamentoCreatedEvent : DomainEvent
    {
        public DepartamentoCreatedEvent(Departamento item)
        {
            Item = item;
        }

        public Departamento Item { get; }
    }

