//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Domain event for when a departamento is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class DepartamentoDeletedEvent : DomainEvent
    {
        public DepartamentoDeletedEvent(Departamento item)
        {
            Item = item;
        }

        public Departamento Item { get; }
    }

