//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Domain event for when a ejemplo is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class EjemploUpdatedEvent : DomainEvent
    {
        public EjemploUpdatedEvent(Ejemplo item)
        {
            Item = item;
        }

        public Ejemplo Item { get; }
    }

