//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-09
// Validator for DeleteDepartamentoCommand: ensures the ID list for departamento is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/departamento
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Commands.Delete;

public class DeleteDepartamentoCommandValidator : AbstractValidator<DeleteDepartamentoCommand>
{
        public DeleteDepartamentoCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

