//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query to retrieve all ejemplos from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Ejemplos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Ejemplos.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Ejemplos.Queries.GetAll;

public class GetAllEjemplosQuery : ICacheableRequest<IEnumerable<EjemploDto>>
{
   public string CacheKey => EjemploCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => EjemploCacheKey.Tags;
}

public class GetAllEjemplosQueryHandler :
     IRequestHandler<GetAllEjemplosQuery, IEnumerable<EjemploDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllEjemplosQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<EjemploDto>> Handle(GetAllEjemplosQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Ejemplos.ProjectTo<EjemploDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


