//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-09
//     Last Modified: 2025-09-09
//     Description: 
//       Defines a query for retrieving departamentos with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Departamentos.DTOs;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Caching;
using CleanArchitecture.Blazor.Application.Features.Departamentos.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Departamentos.Queries.Pagination;

public class DepartamentosWithPaginationQuery : DepartamentoAdvancedFilter, ICacheableRequest<PaginatedData<DepartamentoDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => DepartamentoCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => DepartamentoCacheKey.Tags;
    public DepartamentoAdvancedSpecification Specification => new DepartamentoAdvancedSpecification(this);
}
    
public class DepartamentosWithPaginationQueryHandler :
         IRequestHandler<DepartamentosWithPaginationQuery, PaginatedData<DepartamentoDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public DepartamentosWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<DepartamentoDto>> Handle(DepartamentosWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Departamentos.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Departamento, DepartamentoDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}